vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer : Vich\UploaderBundle\Naming\UniqidNamer
        gallery_image:
            uri_prefix: /images/galleries
            upload_destination: '%kernel.project_dir%/public/images/galleries'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        custom_image:
            uri_prefix: /images/custom
            upload_destination: '%kernel.project_dir%/public/images/custom'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
